spring:
  app:
    prefix: ~
  datasource:
    url: "***URL***"
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties: readOnlyMode=ignore
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARY_MAX:10}
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath*:db/changelog-master.xml

mybatis:
  mapper-locations: classpath*:dao/*.xml
  type-handlers-package: com.kazanexpress.wms.deliverypoint
  configuration:
    map-underscore-to-camel-case: true

wms:
  oauth2:
    enable-authentication: true
    token-service-address: http://account
    enable-worker-info-filter: true
    authorization:
      accessTokenValidity: '86400'
      refreshTokenValidity: '259200'
  locale: "ru"
management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
swagger:
  config:
    context-path: /terminals
logging:
  level:
    root: info
