app:
  prefix: prod-

wms:
  delivery-point:
    fiscaliztion-event:
      enabled: false

  oauth2:
    authorization:
      refreshTokenValidity: '864000'

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}?ApplicationName=${SPRING_DATASOURCE_SERVICE_NAME}&prepareThreshold=${SPRING_DATASOURCE_PREPARE_THRESHOLD}
  kafka:
    producerClientId: prod-${HOSTNAME}
    consumerClientId: prod-${HOSTNAME}
    bootstrapServers: rc1b-96p5j4p85cafv987.mdb.yandexcloud.net:9092

